main:
	make -C cat-0.0.1/
	make -C ls-0.0.1/
clean:
	make -C cat-0.0.1/ clean
	make -C ls-0.0.1/ clean
install:
	make -C cat-0.0.1/ install
	make -C ls-0.0.1/ install
uninstall:
	make -C cat-0.0.1/ uninstall
	make -C ls-0.0.1/ uninstall
